SELECT ?statement
       ?item ?name_ay ?name_es ?name_qu ?name_en
       ?party ?party_name_ay ?party_name_es ?party_name_qu ?party_name_en
       ?district ?district_name_ay ?district_name_es ?district_name_qu ?district_name_en
       ?role ?role_ay ?role_es ?role_qu ?role_en
       ?role_superclass ?role_superclass_ay ?role_superclass_es ?role_superclass_qu ?role_superclass_en
       ?start ?end ?facebook
       ?org ?org_ay ?org_es ?org_qu ?org_en ?org_jurisdiction ?org_seat_count
WHERE {
  BIND(wd:Q18812470 as ?role) .
  BIND(wd:Q1357543 as ?org) .
  OPTIONAL {
  ?org rdfs:label ?org_ay
  FILTER(LANG(?org_ay) = "ay")
}

OPTIONAL {
  ?org rdfs:label ?org_es
  FILTER(LANG(?org_es) = "es")
}

OPTIONAL {
  ?org rdfs:label ?org_qu
  FILTER(LANG(?org_qu) = "qu")
}

OPTIONAL {
  ?org rdfs:label ?org_en
  FILTER(LANG(?org_en) = "en")
}

  OPTIONAL {
    ?org wdt:P1001 ?org_jurisdiction
  }
  OPTIONAL {
    ?org wdt:P1342 ?org_seat_count
  }
  ?item p:P39 ?statement .
  OPTIONAL {
  ?item rdfs:label ?name_ay
  FILTER(LANG(?name_ay) = "ay")
}

OPTIONAL {
  ?item rdfs:label ?name_es
  FILTER(LANG(?name_es) = "es")
}

OPTIONAL {
  ?item rdfs:label ?name_qu
  FILTER(LANG(?name_qu) = "qu")
}

OPTIONAL {
  ?item rdfs:label ?name_en
  FILTER(LANG(?name_en) = "en")
}

  ?statement ps:P39 ?role .
  OPTIONAL {
  ?role rdfs:label ?role_ay
  FILTER(LANG(?role_ay) = "ay")
}

OPTIONAL {
  ?role rdfs:label ?role_es
  FILTER(LANG(?role_es) = "es")
}

OPTIONAL {
  ?role rdfs:label ?role_qu
  FILTER(LANG(?role_qu) = "qu")
}

OPTIONAL {
  ?role rdfs:label ?role_en
  FILTER(LANG(?role_en) = "en")
}

  OPTIONAL {
    ?role wdt:P279 ?role_superclass .
    ?role_superclass wdt:P279+ wd:Q4175034
    OPTIONAL {
  ?role_superclass rdfs:label ?role_superclass_ay
  FILTER(LANG(?role_superclass_ay) = "ay")
}

OPTIONAL {
  ?role_superclass rdfs:label ?role_superclass_es
  FILTER(LANG(?role_superclass_es) = "es")
}

OPTIONAL {
  ?role_superclass rdfs:label ?role_superclass_qu
  FILTER(LANG(?role_superclass_qu) = "qu")
}

OPTIONAL {
  ?role_superclass rdfs:label ?role_superclass_en
  FILTER(LANG(?role_superclass_en) = "en")
}

  }
  
  OPTIONAL { ?statement pq:P580 ?start }
  OPTIONAL { ?statement pq:P582 ?end }
  OPTIONAL {
    ?statement pq:P768 ?district.
    OPTIONAL {
  ?district rdfs:label ?district_name_ay
  FILTER(LANG(?district_name_ay) = "ay")
}

OPTIONAL {
  ?district rdfs:label ?district_name_es
  FILTER(LANG(?district_name_es) = "es")
}

OPTIONAL {
  ?district rdfs:label ?district_name_qu
  FILTER(LANG(?district_name_qu) = "qu")
}

OPTIONAL {
  ?district rdfs:label ?district_name_en
  FILTER(LANG(?district_name_en) = "en")
}

  }
  OPTIONAL {
    ?statement pq:P4100 ?party.
    OPTIONAL {
  ?party rdfs:label ?party_name_ay
  FILTER(LANG(?party_name_ay) = "ay")
}

OPTIONAL {
  ?party rdfs:label ?party_name_es
  FILTER(LANG(?party_name_es) = "es")
}

OPTIONAL {
  ?party rdfs:label ?party_name_qu
  FILTER(LANG(?party_name_qu) = "qu")
}

OPTIONAL {
  ?party rdfs:label ?party_name_en
  FILTER(LANG(?party_name_en) = "en")
}

  }
  OPTIONAL { ?item wdt:P2013 ?facebook }
  BIND(COALESCE(?start, "1000-01-01T00:00:00Z"^^xsd:dateTime) AS ?start_or_sentinel)
BIND(COALESCE(?end, "9999-12-31T00:00:00Z"^^xsd:dateTime) AS ?end_or_sentinel)
FILTER (?end_or_sentinel >= "2018-01-01"^^xsd:dateTime)
FILTER (?start_or_sentinel <= "2018-12-31"^^xsd:dateTime)

} ORDER BY ?item ?role ?start ?end
